### PR TITLE
class social-media applied to img will share image url within Pinterest 

### PR DESCRIPTION
**Pull request by kendrick-k**
Addon : class social-media applied to img will share image url within Pinterest - Kendrick

< img src="image.jpg" class="social-media" /> will be shared with Pinterest

### CODE REVIEW

**Comment by tarungarg** [comment]
go to link: https://github.com/tarungarg/jquery-share 

There i have resolved the pintrest image share issue. 

 Example:  https://github.com/tarungarg/jquery-share/blob/master/example.html

**Comment by flightoffancy** [comment]
openk3, I used your commit to pull in the image for Pinterest and now am getting the error "unable to fetch image". I added the social-media class to my img tag so not sure what is going on.

**Comment by tarungarg** [comment]
Please use my example code and change media(image path)  one time. I think It can help you to check what is wrong. May be the path of the image can be wrong.

**Comment by flightoffancy** [comment]
Thank you! The image is now being pulled in for Pinterest.

Now, since you seem to know your way around this script, is it possible to
have Pinterest pull in the title of the page instead of the description? I
added &title=|t| to the Pinterest line in the code but it is still only
pulling in the description.

Any help is appreciated.

**Pull request closed without merging**
